---
- name: Create user (Linux only)
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    state: present
  when: not is_macos

- name: Create Ansible remote_tmp directory
  become: "{{ not is_macos }}"
  become_user: "{{ user_name }}"
  ansible.builtin.file:
    path: "{{ home_dir }}/.ansible/tmp"
    state: directory
    mode: "0755"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
