---
- name: Generic Workstation Setup
  hosts: all
  gather_facts: true

  roles:
    - role: base
      become: "{{ not is_macos }}"
    - role: packages
      become: "{{ not is_macos }}"
    - role: shell
      become: "{{ not is_macos }}"
    - role: tools
      become: "{{ not is_macos }}"
    - role: dotfiles
      become: "{{ not is_macos }}"
